---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: rust:latest
    environment:
      CARGO_HOME: /var/cache/drone/cargo
    commands:
      - rustup component add clippy
      - cargo build --release
      - cargo clippy --release
      - cargo test --tests --release
      - strip ./target/release/scriptisto
      - bzip2 -f ./target/release/scriptisto
      - pwd
      - ls -lah ./target/release
    volumes:
      - name: cache
        path: /var/cache/drone/cargo
  - name: build-release
    image: rust:latest
    environment:
      CARGO_HOME: /var/cache/drone/cargo
    commands:
      - rustup target add x86_64-unknown-linux-musl
      - apt-get update
      - apt-get install -y musl-tools
      - cargo build --release --target=x86_64-unknown-linux-musl
      - cargo test --tests --release --target=x86_64-unknown-linux-musl
      - strip ./target/x86_64-unknown-linux-musl/release/scriptisto
      - bzip2 -f ./target/x86_64-unknown-linux-musl/release/scriptisto
      - pwd
      - ls -lah ./target/x86_64-unknown-linux-musl/release
    volumes:
      - name: cache
        path: /var/cache/drone/cargo
    when:
      event: tag
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - target/x86_64-unknown-linux-musl/release/scriptisto.bz2
      checksum:
        - sha256
    when:
      event: tag
