---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: rust:latest
    environment:
      CARGO_HOME: /var/cache/drone/cargo
    commands:
      - rustup component add clippy
      - cargo build
      - cargo build --release
      - cargo clippy
      - cargo test --tests
      - cargo test --tests --release
    volumes:
      - name: cache
        path: /var/cache/drone/cargo
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      draft: true
      files:
        - target/release/scriptisto
      checksum:
        - sha256
    when:
      event: tag
