kind: pipeline
name: default

steps:
  build:
    image: rust:latest
    environment:
      - CARGO_HOME=/var/cache/drone/cargo
      - CARGO_TARGET_DIR=/var/cache/drone/cargo
    commands:
      - rustup component add clippy
      - cargo build
      - cargo build --release
      - cargo clippy
      - cargo test --tests
      - cargo test --tests --release
    cache:
      - /var/cache/drone/cargo
  release:
    image: plugins/github-release
    files:
    - target/release/scriptisto
    checksum:
    - sha256
    secrets: [github_token]
    when:
      branch: master
      event: tag
