---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: rust:latest
    environment:
      CARGO_HOME: /var/cache/drone/cargo
    commands:
      - rustup component add clippy
      - cargo build --release
      - cargo clippy --release
      - cargo test --tests --release
      - strip ./target/release/scriptisto
      - bzip2 -f ./target/release/scriptisto
      - pwd
      - ls -lah ./target/release
    volumes:
      - name: cache
        path: /var/cache/drone/cargo
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - target/release/scriptisto.bz2
      checksum:
        - sha256
    when:
      event: tag
